language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

git:
    submodules: false

before_script:
    - npm install
    - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
    - export CHROME_BIN=chromium-browser

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
