language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

addons:
  apt:
    sources:
       - google-chrome
    packages:
    - google-chrome-stable

git:
    submodules: false

before_script:
    - npm install
    - wget http://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo apt-get install libnss3
    - sudo apt-get --only-upgrade install google-chrome-stable
    - sudo cp chromedriver /usr/local/bin/.
    - sudo chmod +x /usr/local/bin/chromedriver
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
