language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

addons:
  firefox: "45.4.0esr"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

git:
    submodules: false

before_script:
    - npm install


script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
